import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], display: 'swap', variable: '--font-inter', });
const poppins = Poppins({ subsets: ["latin"], display: 'swap', weight: "300", variable: '--font-poppins', })

export const metadata: Metadata = {
  title: "ReelRecGuide",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="apple-touch-icon" sizes="180x180" href="/logo/apple-touch-icon.png" />
      <link rel="icon" type="image/png" sizes="32x32" href="/logo/favicon_io /favicon-32x32.png" />
      <link rel="icon" type="image/png" sizes="16x16" href="/logo/favicon_io /favicon-16x16.png" />
      <body className={`${inter.className} ${poppins.className}`}>{children}</body>
    </html>
  );
}
